# Generated by Django 6.0.7 on 2026-07-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cellulose', 'Cellulose Ether'), ('polymer', 'Polymer Additives'), ('titanium', 'Titanium Dioxide'), ('chemical', 'Chemical Additives'), ('mineral', 'Mineral Fillers')], max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
