# Generated by Django 6.0.7 on 2026-07-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='temp-slug', unique=True),
            preserve_default=False,
        ),
    ]
